### ISSUE TITLE
Dependency fast_double_parser.h not found

### ISSUE THREAD

**Issue by MaggieWang0614** [andrewherren/StochasticTree#1]
Hi Drew, I encountered this error while trying to install the package. Any idea where I can get this dependency?

```
In file included from /path/to/StochasticTree/src/config.cpp:5:
In file included from /path/to/StochasticTree/include/stochtree/config.h:8:
/path/to/StochasticTree/include/stochtree/common.h:32:10: fatal error: '../../dependencies/fast_double_parser/include/fast_double_parser.h' file not found
#include "../../dependencies/fast_double_parser/include/fast_double_parser.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```
Thanks.

**Comment by andrewherren** [comment]
Thanks for raising this! I have `fast_double_parser` included as a git submodule [here](https://github.com/andrewherren/StochasticTree/tree/main/dependencies), but it's likely that when you cloned the repo, it didn't include the submodules by default. Can you try cloning the repo with `git clone --recursive`? 

If that works, I'll add it to the docs.
