### ISSUE TITLE
[python] BART seems not to work on a particular dataset, for reasons mysterious to me

### ISSUE THREAD

**Issue by Gattocrucco** [andrewherren/StochasticTree#19]
I have a dataset on which the predictions of `BART` are totally off. This does not change if I burn 1000 samples instead of the default 100.

On fake data generated from a linear model, matching the marginal moments to the real data, it works ok.

The existing BART packages do just fine.

I can't share the data publicly, I will send it to you privately.

Hopefully the reason is some simple configuration/setting issue I'm not aware of (say, some required form of standardization of the covariates).

```python
import stochtree
import numpy as np
from matplotlib import pyplot as plt

# load problematic data
xy = np.load('xy.npz')
X = xy['X']
y = xy['y']

# simulate superficially similar data (moments are approx matched)
rng = np.random.default_rng(0)
X_sim = rng.multivariate_normal(np.mean(X, axis=0), np.cov(X.T), size=len(X))
assert X_sim.shape == X.shape
y_rng = np.std(y) * rng.standard_normal(len(y))
beta, _, _, _ = np.linalg.lstsq(X_sim, y_rng, rcond=None)
y_sim = np.mean(y) + X_sim @ beta + np.std(y) * rng.standard_normal(len(y))

# fit real data with bart
bart = stochtree.BART()
bart.sample(X, y, num_burnin=1000)
yhat_samples = bart.predict(X)
yhat = np.mean(yhat_samples, axis=1)

# fit fake data with bart
bart_sim = stochtree.BART()
bart_sim.sample(X_sim, y_sim)
yhat_samples_sim = bart_sim.predict(X_sim)
yhat_sim = np.mean(yhat_samples_sim, axis=1)

# plot fit vs. data
fig, axs = plt.subplots(2, 2, num='prova_dati', clear=True, figsize=(8, 8), layout='constrained')
for ax, yhat_, y_, label in zip(axs[0], [yhat, yhat_sim], [y, y_sim], ['real data', 'fake data']):
    ax.set(xlabel='Y_fit', ylabel='Y_data', title=label)
    ax.plot(yhat_, y_, '.')
    ax.plot(yhat_, yhat_, '-')

# plot data distribution
axs[1, 0].set(xlabel='Y', ylabel='bin count', title='Y distribution')
axs[1, 0].hist(y, bins='auto', histtype='step')
axs[1, 1].set(xlabel='X (all covariates)', ylabel='bin count', title='X distribution')
axs[1, 1].hist(X.reshape(-1), bins='auto', histtype='step')

plt.show()
```

![immagine](https://github.com/andrewherren/StochasticTree/assets/9684110/54d1f47c-f4fa-4cdf-a899-95782b7903c2)

**Comment by Gattocrucco** [comment]
Update: I tried rescaling all covariates to lie in $[0, 1]$, and then dropped the mostly zero covariates (some dummies). It still does not work:

### Rescaled covariates

```py
X = (X - X.min(0)) / (X.max(0) - X.min(0))
```

![immagine](https://github.com/andrewherren/StochasticTree/assets/9684110/e830bea8-ea99-492c-a076-c8f9c9a36d62)

### Rescaled and filtered covariates

```py
X = (X - X.min(0)) / (X.max(0) - X.min(0))
X = X[:, np.count_nonzero(X == 0, axis=0) < 0.5 * len(X)]
```

![immagine](https://github.com/andrewherren/StochasticTree/assets/9684110/c52d66ca-e694-465e-9942-c41abc529673)

**Comment by Gattocrucco** [comment]
The predicted Y seem to match the range of X.

**Comment by Gattocrucco** [comment]
Found the problem: my data file is column-major, and the package assumes that all numpy arrays are row-major.

**Comment by andrewherren** [comment]
Thank you for uncovering this! I will add checks to the python / R layers before passing to C++ with that (erroneous) assumption.
